# 实时加载配置
live_config_reload = true

[shell]
program = "pwsh.exe"

# 窗口
[window]
# 背景透明度
opacity = 0.9
dimensions = { columns = 120, lines = 30 }

# 字体
[font]
# 字体大小
size = 12
# 字体风格
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
italic = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
# 光标样式
[cursor]
style = { shape = "Beam", blinking = "On" }

[keyboard]
bindings = [
    { key = "Return", mods = "Alt", action = "None" },
    { key = "F11", mods = "None", action = "ToggleFullscreen" }
]
