gui:
  language: 'en'
os:
  edit: 'nvim -u $LOCALAPPDATA/nvim/init_noplugin.lua {{filename}}'
  editAtLine: 'nvim -u $LOCALAPPDATA/nvim/init_noplugin.lua +{{line}} {{filename}}'
  editInTerminal: true
  openDirInEditor: 'nvim -u $LOCALAPPDATA/nvim/init_noplugin.lua {{dir}}'
