gui:
  language: 'en'
os:
  edit: 'nvim -u $NVIM_CONF_HOME/init_min.lua {{filename}}'
  editAtLine: 'nvim -u $NVIM_CONF_HOME/init_min.lua +{{line}} {{filename}}'
  editInTerminal: true
  openDirInEditor: 'nvim -u $NVIM_CONF_HOME/init_min.lua {{dir}}'
